# Dockstore config version, not pipeline version
version: master
workflows:
  - subclass: nfl
    # primaryDescriptorPath: /nextflow.config
    primaryDescriptorPath: /main.nf
    readMePath: /README.md
    publish: True
