# Dockstore config version, not pipeline version
version: master
workflows:
  - subclass: nfl
    primaryDescriptorPath: /nextflow.config
    # primaryDescriptorPath: /main.nf
    # testParameterFiles: 
    #   - /conf/test.config
    readMePath: /README.md
    publish: True
