sudo: required
language: python
jdk: openjdk8
services: docker
python: '3.6'
matrix:
  fast_finish: true
install:
  - mkdir /tmp/nextflow
  - cd /tmp/nextflow
  - wget -qO- get.nextflow.io | bash
  - sudo ln -s /tmp/nextflow/nextflow /usr/local/bin/nextflow
  - mkdir ${TRAVIS_BUILD_DIR}/tests && cd ${TRAVIS_BUILD_DIR}/tests
  - VERSION=2.5.2
  - wget https://github.com/singularityware/singularity/releases/download/$VERSION/singularity-$VERSION.tar.gz
  - tar xvf singularity-$VERSION.tar.gz
  - cd singularity-$VERSION
  - ./configure --prefix=/usr/local
  - make
  - sudo make install
  
env:
  matrix:
    - NXF_VER=20.06.0

script:
  - nextflow run takudzwa-coder/chipimputation -profile test,singularity
